### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by kirus21** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-kirus21#1]
[Infografia Realidad Aumentada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-kirus21/files/10746406/Infografia.Realidad.Aumentada.pdf)

**Comment by bg55-a** [comment]
calificacion: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
